baseURL: http://example.org/
languageCode: en-us
title: "The syndrome imposter"
theme: "toha"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true

# Enable Disqus forum
# optional
disqusShortname: thesyndromeimposter
