baseURL: http://example.org/
languageCode: en-us
title: "Toha"
theme: "toha"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true

# Enable Google Analytics
googleAnalytics: <your google analytics id>

# Enable Disqus forum
# optional
disqusShortname: <your disqus short code>

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  # Github Repo URL. This is used to add "Improve This Page" button
  gitRepo: <your site's Github repo URL>